# frozen_string_literal: true

require 'rake'
require 'colorize'
require 'active_record'
require 'yaml'

Dir.chdir File.dirname(__FILE__)

Dir.glob('*').select { |file| File.directory? file }.each do |dir|
  require_relative "#{dir}.rb"
  Dir.glob("#{dir}/lib/rake/*.rake").each { |r| import r }
end

